services:
  mysql:
    image: mysql:8.0
    container_name: ringle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ringle_db
      MYSQL_USER: ringle
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: ringle-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql-data:
