spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/ringle_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ringle
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
